version: '3.9'

services:
  frontend:
    build:
      context: ./apps/client
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - '3000:80' # serve React on http://localhost:3000
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./apps/server
      dockerfile: Dockerfile
    container_name: express-backend
    ports:
      - '4000:4000' # API exposed on http://localhost:4000
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/mydb
      - ORS_API_KEY=${ORS_API_KEY} # forward your env var
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    container_name: postgres-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  db_data:
    driver: local
