name: Trigger auto deployment for ocs-server

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/ocs-server-AutoDeployTrigger-65947d68-7e9b-4f10-ad0d-67843b7eee30.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.OCSSERVER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.OCSSERVER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.OCSSERVER_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/apps/server
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: docker.io
          registryUsername: ${{ secrets.OCSSERVER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.OCSSERVER_REGISTRY_PASSWORD }}
          containerAppName: ocs-server
          resourceGroup: ocs-server
          imageToBuild: forkedupduck/ocs-server:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


